print("sinh viên: TRAN VAN TRUNG")
print("MSV:245752021610133")
ds = input("Nhập các phần tử của list (cách nhau bằng khoảng trắng): ").split()
print("\nList ban đầu:", ds)
ds.sort()
print("\nList sau khi sắp xếp:", ds)
